// packages/react-native/src/Ms.tsx
import { forwardRef, type ReactNode } from 'react';
import { Text, type TextProps, type TextStyle, type StyleProp } from 'react-native';

export type MsVariant = 'outlined' | 'outline' | 'rounded' | 'sharp';
export type MsGrade = -25 | 0 | 200 | number;

/**
 * Mapping variant → font family.
 * Konsumen wajib me-load font via expo-font atau Font.loadAsync()
 * dengan key family `MaterialSymbolsOutlined`, `MaterialSymbolsRounded`,
 * `MaterialSymbolsSharp`. Lihat README package.
 */
export const FONT_FAMILY: Record<'outlined' | 'rounded' | 'sharp', string> = {
    outlined: 'MaterialSymbolsOutlined',
    rounded: 'MaterialSymbolsRounded',
    sharp: 'MaterialSymbolsSharp',
};

export interface MsBaseProps extends Omit<TextProps, 'style'> {
    icon?: string;
    code?: string;
    variant?: MsVariant;
    size?: number;
    color?: string;
    /**
     * Catatan: di React Native, `font-variation-settings` tidak didukung
     * di semua engine. Prop `fill` saat ini diabaikan kecuali konsumen
     * me-load font khusus weight/fill yang diinginkan.
     */
    fill?: boolean;
    /** @deprecated Tidak applicable di RN. */
    grad?: MsGrade;
    /** @deprecated Tidak applicable di RN. */
    strokeWidth?: number;
    /** @deprecated Tidak applicable di RN. */
    opticalSize?: number;
    style?: StyleProp<TextStyle>;
    children?: ReactNode;
}

export type MsProps = MsBaseProps;

export interface MsInternalProps extends MsBaseProps {
    /** @internal */ __iconName?: string;
}

function normalizeVariant(v: MsVariant | undefined): 'outlined' | 'rounded' | 'sharp' {
    if (!v || v === 'rounded') return 'rounded';
    if (v === 'outline' || v === 'outlined') return 'outlined';
    return 'sharp';
}

export function codeToChar(code: string): string {
    const cp = parseInt(code, 16);
    if (Number.isNaN(cp)) return '';
    return String.fromCodePoint(cp);
}

export const Ms = forwardRef<InstanceType<typeof Text>, MsProps>(function Ms(props, ref) {
    return renderMs(props, ref);
});

export function renderMs(
    props: MsInternalProps,
    ref: React.ForwardedRef<InstanceType<typeof Text>>,
) {
    const {
        icon, code, variant, size, color,
        fill: _fill, grad: _grad, strokeWidth: _strokeWidth, opticalSize: _opticalSize,
        style, children,
        __iconName,
        ...rest
    } = props;

    const v = normalizeVariant(variant);
    const fontFamily = FONT_FAMILY[v];

    const baseStyle: TextStyle = {
        fontFamily,
        ...(size !== undefined ? { fontSize: size } : null),
        ...(color !== undefined ? { color } : null),
    };

    const finalStyle: StyleProp<TextStyle> = style ? [baseStyle, style] : baseStyle;

    let body: ReactNode;
    if (children !== undefined && children !== null) body = children;
    else if (code) body = codeToChar(code);
    else body = __iconName ?? icon ?? null;

    return (
        <Text ref={ref} accessibilityElementsHidden {...rest} style={finalStyle}>
            {body}
        </Text>
    );
}

// packages/solid/src/Ms.tsx
import { splitProps, mergeProps, type JSX, type Component } from 'solid-js';

export type MsVariant = 'outlined' | 'outline' | 'rounded' | 'sharp';
export type MsGrade = -25 | 0 | 200 | number;

export interface MsBaseProps extends JSX.HTMLAttributes<HTMLSpanElement> {
    icon?: string;
    code?: string;
    variant?: MsVariant;
    size?: number | string;
    color?: string;
    fill?: boolean;
    grad?: MsGrade;
    strokeWidth?: number;
    opticalSize?: number;
}

export type MsProps = MsBaseProps;

export function variantClass(variant: MsVariant): string {
    const v = variant === 'outline' ? 'outlined' : variant;
    return `material-symbols-${v}`;
}

export function codeToChar(code: string): string {
    const cp = parseInt(code, 16);
    if (Number.isNaN(cp)) return '';
    return String.fromCodePoint(cp);
}

export function buildFontVariationSettings(opts: {
    fill?: boolean;
    grad?: number;
    strokeWidth?: number;
    opticalSize?: number;
}): string | undefined {
    const parts: string[] = [];
    if (opts.fill) parts.push("'FILL' 1");
    if (opts.grad !== undefined && opts.grad !== 0) parts.push(`'GRAD' ${opts.grad}`);
    if (opts.strokeWidth !== undefined && opts.strokeWidth !== 400) parts.push(`'wght' ${opts.strokeWidth}`);
    if (opts.opticalSize !== undefined && opts.opticalSize !== 48) parts.push(`'opsz' ${opts.opticalSize}`);
    return parts.length ? parts.join(', ') : undefined;
}

export interface MsInternalProps extends MsBaseProps {
    /** @internal */ __iconName?: string;
    /** @internal */ __iconClass?: string;
}

/**
 * Generic component.
 */
export const Ms: Component<MsProps> = (rawProps) => {
    return renderMs(rawProps);
};

export function renderMs(rawProps: MsInternalProps): JSX.Element {
    const merged = mergeProps({ variant: 'rounded' as MsVariant }, rawProps);
    const [local, rest] = splitProps(merged as any, [
        'icon', 'code', 'variant', 'size', 'color', 'fill', 'grad',
        'strokeWidth', 'opticalSize', 'class', 'classList', 'style',
        'children', '__iconName', '__iconClass', 'aria-label',
    ]);

    // Solid components are reactive; we keep accessors via getters so
    // updates propagate without manual signal usage.
    const styleAccessor = () => {
        const fvs = buildFontVariationSettings({
            fill: local.fill,
            grad: local.grad,
            strokeWidth: local.strokeWidth,
            opticalSize: local.opticalSize,
        });
        const baseStyle = typeof local.style === 'object' && local.style ? local.style : {};
        return {
            ...(local.size !== undefined ? { 'font-size': typeof local.size === 'number' ? `${local.size}px` : local.size } : null),
            ...(local.color !== undefined ? { color: local.color } : null),
            ...(fvs ? { 'font-variation-settings': fvs } : null),
            ...baseStyle,
        };
    };

    const classAccessor = () =>
        [variantClass(local.variant!), local.__iconClass, local.class].filter(Boolean).join(' ');

    const bodyAccessor = (): JSX.Element => {
        if (local.children !== undefined && local.children !== null) return local.children as JSX.Element;
        if (local.code) return codeToChar(local.code);
        const resolved = local.__iconName ?? local.icon;
        return resolved ?? null;
    };

    const ariaHidden = () => (local['aria-label'] ? undefined : true);

    return (
        <span
            aria-hidden={ariaHidden()}
            aria-label={local['aria-label']}
            {...rest}
            class={classAccessor()}
            style={styleAccessor()}
        >
            {bodyAccessor()}
        </span>
    );
}
